### ISSUE TITLE
Normalisation by non integers does not work

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#21]
Automatic sequence processing leads to values for sequenincg depth that are not always integers. Decimal numbers like 7.1 will cause error.

**Comment by culpinnis** [comment]
This will take some time, because the change to another data structure involves the modification of all used functions. 
At the moment the output (occ) is rounded to integers - should this still be done in the next version?
Easiest way could be to convert the decimal value to an integer in perl before calling the cmasker. Is this an option? - I don't think that the decimal value will have a great influence on the following masking process (because we will merge the different repeat regions together anyway).

**Comment by tschmutzer** [comment]
Yes - in all OCC files only rounded numbers (integers) are allowed. The point is that the normalisation now can be based on an decimal number (e.g. 7.1). We should be precise here and should not round 'sequencing depth' value which is used for normalisation.

However, we should take care about output file naming. Right now, normalized files name are using an infix N + value. The dot in e.g. '7.1' crashes the filesnames! Thats why we should not code the value '7.1' or '7' in the filename. 

Does this solve the issue regaring usage of non integer values in normalisation?

**Comment by culpinnis** [comment]
Okay, then I have to remove the N+value from the output file name. 
Okay I will try to renew the code, but in fact I need to change all declarations and functions to allocate a float instead of an integer (starting at the function which reads in the variables and converts char-arrays to integers, ending at the functions which does the calculation) - I will try to finish and test it until the end of the week.

**Comment by culpinnis** [comment]
Hopefully fixed with commit 1947f56 
We need to change some parts of the run functions because I have changed the naming of the normalized files to just _NORM_ instead of N + Value.
